spring.application.name=DevOps_SDAT_QAP4


spring.datasource.url=jdbc:mysql://localhost:3306/tournament_manager
spring.datasource.username=root
spring.datasource.password=Abcd23452345!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update